"""Generates rtl/common/phy_soft_pkg.sv: tables and constants of the soft receiver back-end from python/phy2_fixed_ref.py."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
import numpy as np
import phy2_fixed_ref as F

L = ["// GENERATED by python/gen_soft_pkg.py from python/phy2_fixed_ref.py. Do not edit.", "package phy_soft_pkg;"]
L.append(f"  localparam int LGF = {F.LGF};              // log2 steps per octave")
L.append(f"  localparam int LGMB = {F.LGM};             // mantissa bits of the log lookup")
L.append(f"  localparam int CNU = {F.CNU};            // log code offset: nu = 0.9 * mean guard energy")
L.append(f"  localparam int D_MIN = {F.D_MIN};")
L.append(f"  localparam int D_MAX = {F.D_MAX};")
L.append(f"  localparam int D_STEP = {F.D_STEP};")
L.append(f"  localparam int NMU = {len(F.MU_T)};            // table entries")
L.append(f"  localparam int SH_C = {F.SH_C};             // LLR scale constant: shift = SH_C - gain exponent")
L.append(f"  localparam int GUARD_LO = {int(F.GUARD[0])};      // guard bins (noise only) of the FFT frame")
L.append(f"  localparam int GUARD_HI = {int(F.GUARD[-1])};")
L.append(f"  localparam int LLR_MAXV = {F.LLR_MAX};")
def arr(name, vals, w, signed=False):
    L.append(f"  localparam logic {'signed ' if signed else ''}[{w-1}:0] {name} [{len(vals)}] = '{{")
    items = []
    for v in vals:
        v = int(v)
        items.append(f"{w}'sd{v}" if signed and v >= 0 else (f"-{w}'sd{-v}" if signed else f"{w}'d{v}"))
    for i in range(0, len(items), 8):
        L.append("    " + ", ".join(items[i:i+8]) + ("," if i + 8 < len(items) else ""))
    L.append("  };")
arr("LGT_ROM", F.LGT, 6)
arr("EXP2_ROM", F.EXP2_T, 6)
arr("MU_ROM", F.MU_T, 16)
arr("GLM_ROM", F.GL_MMSE_T, 12, True)
arr("GLZ_ROM", F.GL_ZF_T, 12, True)
L.append("endpackage")
out = os.path.join(os.path.dirname(__file__), "..", "rtl", "common", "phy_soft_pkg.sv")
open(out, "w").write("\n".join(L) + "\n")
print("wrote", os.path.abspath(out), "NMU", len(F.MU_T), "CNU", F.CNU)
