"""Generates rtl/common/phy_ldpc_pkg.sv (code tables of the RTL encoder / decoder) from ldpc_ref.CODES.
Two codes share one datapath, selected by `cs` (0 = rate 1/2, MAX RANGE; 1 = rate 5/6, MAX RATE): N = 2160, Z = 60, 36 block columns,
18 / 6 block rows.
Column rotation bookkeeping of the decoder: every column is stored rotated by the shift of the last layer that used it
(COL_OFF); per layer entry the RTL rotates by DELTA = (shift - offset left by the previous user of the column) mod Z."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
import numpy as np
import ldpc_ref as lr

Z, NB = lr.Z, lr.NB
CODE_ORDER = [("r12", 0), ("r56", 1)]          # (name, cs)


def tables(base):
    mb = base.shape[0]
    kb = NB - mb
    ent = [[(j, int(base[i, j])) for j in range(NB) if base[i, j] >= 0] for i in range(mb)]
    deg = [len(e) for e in ent]
    dmax = max(deg)
    off_last = {}
    for i in range(mb):
        for j, s in ent[i]:
            off_last[j] = s
    cur = dict(off_last)
    delta = [[0] * dmax for _ in range(mb)]
    for i in range(mb):
        for k, (j, s) in enumerate(ent[i]):
            delta[i][k] = (s - cur[j]) % Z
            cur[j] = s
    assert all(cur[j] == off_last[j] for j in off_last)
    enc = [[(j, int(base[i, j])) for j in range(kb) if base[i, j] >= 0] for i in range(mb)]
    return dict(mb=mb, kb=kb, ent=ent, deg=deg, dmax=dmax, off=off_last, delta=delta, enc=enc, a=int(base[0, kb]), mid=mb // 2)


T = {cs: tables(lr.CODES[name]) for name, cs in CODE_ORDER}
LMBX = max(t["mb"] for t in T.values())
LKBX = max(t["kb"] for t in T.values())
DMAX = max(t["dmax"] for t in T.values())

L = []
A = L.append
A("// GENERATED by python/gen_ldpc_pkg.py from python/ldpc_ref.py (CODES). Do not edit.")
A("package phy_ldpc_pkg;")
A(f"  localparam int LZ = {Z};            // circulant size")
A(f"  localparam int LMB = {LMBX};          // block rows (layers) of the largest code")
A(f"  localparam int LNB = {NB};          // block columns")
A(f"  localparam int LKB = {LKBX};          // information block columns of the largest code")
A(f"  localparam int LDMAX = {DMAX};         // maximum layer degree over both codes")
A("  localparam int LN = LZ * LNB;       // codeword bits (both codes)")
A("  localparam int LK = LZ * LKB;       // information bits of the largest code (rate 5/6)")
A("  // code select: 0 = rate 1/2 (MAX RANGE, QPSK), 1 = rate 5/6 (MAX RATE, 16-QAM)")
A("")
A("  function automatic int lmb(input int cs);        // layers")
A(f"    return cs == 0 ? {T[0]['mb']} : {T[1]['mb']};")
A("  endfunction")
A("  function automatic int lkb(input int cs);        // information block columns")
A(f"    return cs == 0 ? {T[0]['kb']} : {T[1]['kb']};")
A("  endfunction")
A("  function automatic int lpa(input int cs);        // shift 'a' of the first parity column (rows 0 and lmb-1)")
A(f"    return cs == 0 ? {T[0]['a']} : {T[1]['a']};")
A("  endfunction")
A("  function automatic int lmid(input int cs);       // row of the shift-0 entry of the first parity column")
A(f"    return cs == 0 ? {T[0]['mid']} : {T[1]['mid']};")
A("  endfunction")
A("")
A("  // decoder: layer degree, entry column, rotation delta (6 bit each); key = cs * 1024 + layer * 32 + entry")
A("  function automatic int ldeg(input int cs, input int l);")
A("    case (cs * 32 + l)")
for cs, t in T.items():
    for i in range(t["mb"]):
        A(f"      {cs * 32 + i}: return {t['deg'][i]};")
A("      default: return 0;")
A("    endcase")
A("  endfunction")
A("  function automatic logic [5:0] lcol(input int cs, input int l, input int e);")
A("    case (cs * 1024 + l * 32 + e)")
for cs, t in T.items():
    for i in range(t["mb"]):
        for k, (j, s) in enumerate(t["ent"][i]):
            A(f"      {cs * 1024 + i * 32 + k}: return 6'd{j};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("  function automatic logic [5:0] ldelta(input int cs, input int l, input int e);")
A("    case (cs * 1024 + l * 32 + e)")
for cs, t in T.items():
    for i in range(t["mb"]):
        for k in range(t["deg"][i]):
            A(f"      {cs * 1024 + i * 32 + k}: return 6'd{t['delta'][i][k]};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("  function automatic logic [5:0] lshift(input int cs, input int l, input int e);   // circulant shift of the entry (rotation state after its write-back)")
A("    case (cs * 1024 + l * 32 + e)")
for cs, t in T.items():
    for i in range(t["mb"]):
        for k, (j, s) in enumerate(t["ent"][i]):
            A(f"      {cs * 1024 + i * 32 + k}: return 6'd{s};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("  // offset (rotation) in which every column is stored at load (= left by the last layer of the previous iteration)")
A("  function automatic logic [5:0] lcoloff(input int cs, input int c);")
A("    case (cs * 64 + c)")
for cs, t in T.items():
    for j in range(NB):
        A(f"      {cs * 64 + j}: return 6'd{t['off'][j]};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("")
A("  // encoder: information entries per block row (column, shift); the information bytes of a code with fewer information columns")
A("  // end up in the low bits of the 1800 bit register, so the column index is offset by (LKB - kb)")
A("  function automatic int enc_n(input int cs, input int r);")
A("    case (cs * 32 + r)")
for cs, t in T.items():
    for i in range(t["mb"]):
        A(f"      {cs * 32 + i}: return {len(t['enc'][i])};")
A("      default: return 0;")
A("    endcase")
A("  endfunction")
A("  function automatic logic [5:0] enc_col(input int cs, input int r, input int k);")
A("    case (cs * 1024 + r * 32 + k)")
for cs, t in T.items():
    off = LKBX - t["kb"]
    for i in range(t["mb"]):
        for k, (j, s) in enumerate(t["enc"][i]):
            A(f"      {cs * 1024 + i * 32 + k}: return 6'd{j + off};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("  function automatic logic [5:0] enc_sh(input int cs, input int r, input int k);")
A("    case (cs * 1024 + r * 32 + k)")
for cs, t in T.items():
    for i in range(t["mb"]):
        for k, (j, s) in enumerate(t["enc"][i]):
            A(f"      {cs * 1024 + i * 32 + k}: return 6'd{s};")
A("      default: return 6'd0;")
A("    endcase")
A("  endfunction")
A("endpackage")
out = os.path.join(os.path.dirname(__file__), "..", "rtl", "common", "phy_ldpc_pkg.sv")
open(out, "w").write("\n".join(L) + "\n")
print("wrote", os.path.abspath(out), {cs: (t["mb"], t["deg"], t["dmax"]) for cs, t in T.items()})
