"""Generates rtl/common/phy_ldpc_pkg.sv (code tables of the RTL encoder / decoder) from ldpc_ref.H_BASE.
Column rotation bookkeeping of the decoder: every column is stored rotated by the shift of the last layer that used it
(COL_OFF); per layer entry the RTL rotates by DELTA = (shift - offset left by the previous user of the column) mod Z."""
import os, sys
sys.path.insert(0, os.path.dirname(__file__))
import numpy as np
import ldpc_ref as lr

base = lr.H_BASE
Z, MB, NB, KB = lr.Z, lr.MB, lr.NB, lr.KB
ent = [[(j, int(base[i, j])) for j in range(NB) if base[i, j] >= 0] for i in range(MB)]
DEG = [len(e) for e in ent]
DMAX = max(DEG)
off_last = {}
for i in range(MB):
    for j, s in ent[i]:
        off_last[j] = s
cur = dict(off_last)             # state before the first layer of an iteration = offset left by the last layer of the previous one
delta = [[0] * DMAX for _ in range(MB)]
for i in range(MB):
    for k, (j, s) in enumerate(ent[i]):
        delta[i][k] = (s - cur[j]) % Z
        cur[j] = s
assert all(cur[j] == off_last[j] for j in off_last)

# encoder tables: info part entries per block row (column, shift) and parity structure
enc = [[(j, int(base[i, j])) for j in range(KB) if base[i, j] >= 0] for i in range(MB)]
a = int(base[0, KB])

L = []
L.append("// GENERATED by python/gen_ldpc_pkg.py from python/ldpc_ref.py (H_BASE). Do not edit.")
L.append("package phy_ldpc_pkg;")
L.append(f"  localparam int LZ = {Z};            // circulant size")
L.append(f"  localparam int LMB = {MB};           // block rows (layers)")
L.append(f"  localparam int LNB = {NB};          // block columns")
L.append(f"  localparam int LKB = {KB};          // information block columns")
L.append(f"  localparam int LDMAX = {DMAX};         // maximum layer degree")
L.append(f"  localparam int LN = LZ * LNB;       // codeword bits")
L.append(f"  localparam int LK = LZ * LKB;       // information bits")
L.append(f"  localparam int LPA = {a};            // shift 'a' of the first parity column (rows 0 and LMB-1)")
L.append(f"  localparam int LMID = {MB // 2};            // row of the shift-0 entry of the first parity column")
L.append("")
L.append("  // decoder: layer degree, entry column, rotation delta (6 bit each)")
L.append("  function automatic int ldeg(input int l);")
L.append("    case (l)")
for i in range(MB):
    L.append(f"      {i}: return {DEG[i]};")
L.append("      default: return 0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  function automatic logic [5:0] lcol(input int l, input int e);")
L.append("    case (l * 32 + e)")
for i in range(MB):
    for k, (j, s) in enumerate(ent[i]):
        L.append(f"      {i * 32 + k}: return 6'd{j};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  function automatic logic [5:0] ldelta(input int l, input int e);")
L.append("    case (l * 32 + e)")
for i in range(MB):
    for k in range(DEG[i]):
        L.append(f"      {i * 32 + k}: return 6'd{delta[i][k]};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  function automatic logic [5:0] lshift(input int l, input int e);   // circulant shift of the entry (rotation state after its write-back)")
L.append("    case (l * 32 + e)")
for i in range(MB):
    for k, (j, s) in enumerate(ent[i]):
        L.append(f"      {i * 32 + k}: return 6'd{s};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  // offset (rotation) in which every column is stored at load (= left by the last layer of the previous iteration)")
L.append("  function automatic logic [5:0] lcoloff(input int c);")
L.append("    case (c)")
for j in range(NB):
    L.append(f"      {j}: return 6'd{off_last[j]};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("")
L.append("  // encoder: information entries per block row (column, shift); 3 per information column")
L.append("  function automatic int enc_n(input int r);")
L.append("    case (r)")
for i in range(MB):
    L.append(f"      {i}: return {len(enc[i])};")
L.append("      default: return 0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  function automatic logic [5:0] enc_col(input int r, input int k);")
L.append("    case (r * 32 + k)")
for i in range(MB):
    for k, (j, s) in enumerate(enc[i]):
        L.append(f"      {i * 32 + k}: return 6'd{j};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("  function automatic logic [5:0] enc_sh(input int r, input int k);")
L.append("    case (r * 32 + k)")
for i in range(MB):
    for k, (j, s) in enumerate(enc[i]):
        L.append(f"      {i * 32 + k}: return 6'd{s};")
L.append("      default: return 6'd0;")
L.append("    endcase")
L.append("  endfunction")
L.append("endpackage")
out = os.path.join(os.path.dirname(__file__), "..", "rtl", "common", "phy_ldpc_pkg.sv")
open(out, "w").write("\n".join(L) + "\n")
print("wrote", os.path.abspath(out), "deg", DEG, "dmax", DMAX)
